#!/usr/local/bin/perl -w

my $title = 'TITLE';
if (defined($ARGV[0]) and length($ARGV[0])) {
  if(substr($ARGV[0],0,1) ne '-') {
    $title = join(' ',@ARGV);
  } else {
    print "$0: usage: bhtml [Page Title]\n";
    print "\nDumps a basic html page to STDOUT.\n";
    exit(2);
  }
}

print <<"HTMLPAGE";
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>$title</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style type=text/css><!--
Body {background:white; color: black; }
H1 { font-weight: bold; font-size: 18px }
H2 { font-weight: normal; font-size: 18px }
:link { color: blue; } 
:link:hover {color:red;}
:link:visited {color:red;}
--></style>
</head>
<body>
<h1>$title</h1>
<div>
Body
</div>
</body>
</html>
HTMLPAGE

__END__
<html>
<head>
<title>$title</title>
</head>
<body bgcolor=white text=black link=blue vlink=red>
<h2>$title</h2>
<p>
Body
</p>
</body>
</html>

