#!/bin/sh
size=80x16
col1=0 
col2=504
col3=1008
row1=0 
row2=241
row3=482 
row4=723

xterm -geometry $size+$col1+$row1 &
xterm -geometry $size+$col1+$row2 &
xterm -geometry $size+$col1+$row3 &
xterm -geometry $size+$col1+$row4 &

xterm -geometry $size+$col2+$row1 &
xterm -geometry $size+$col2+$row2 &
xterm -geometry $size+$col2+$row3 &
xterm -geometry $size+$col2+$row4 &

xterm -geometry $size+$col3+$row1 &
xterm -geometry $size+$col3+$row2 &
xterm -geometry $size+$col3+$row3 &
xterm -geometry $size+$col3+$row4 &
