#!/bin/ksh
# run three xterms along the top

size=80x24
col1=+0
col2=+504
col3=+1008
row1=+10

xterm -geometry $size$col1$row1 $@ &
xterm -geometry $size$col2$row1 $@ &
xterm -geometry $size$col3$row1 $@ &

exit
